"""empty message

Revision ID: 3b976e614853
Revises: 
Create Date: 2023-05-24 22:21:25.168043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b976e614853'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_tracker_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('fullname', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food_tracker_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_tracker_users_fullname'), ['fullname'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_tracker_users_username'), ['username'], unique=True)

    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=64), nullable=True),
    sa.Column('protein', sa.Integer(), nullable=False),
    sa.Column('carbohydrates', sa.Integer(), nullable=False),
    sa.Column('fat', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_foods_food_name'), ['food_name'], unique=False)

    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('food_selection', sa.String(length=144), nullable=False),
    sa.ForeignKeyConstraint(['food_selection'], ['foods.food_name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['food_tracker_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entries')
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_foods_food_name'))

    op.drop_table('foods')
    with op.batch_alter_table('food_tracker_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_tracker_users_username'))
        batch_op.drop_index(batch_op.f('ix_food_tracker_users_fullname'))

    op.drop_table('food_tracker_users')
    # ### end Alembic commands ###
