"""empty message

Revision ID: b8d94414fe26
Revises: bf9d71262c3f
Create Date: 2023-05-24 23:57:05.737009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d94414fe26'
down_revision = 'bf9d71262c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.alter_column('food_selection',
               existing_type=sa.VARCHAR(length=144),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint('entries_food_selection_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'foods', ['food_selection'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('entries_food_selection_fkey', 'foods', ['food_selection'], ['food_name'])
        batch_op.alter_column('food_selection',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=144),
               existing_nullable=False)

    # ### end Alembic commands ###
