"""empty message

Revision ID: bf9d71262c3f
Revises: c4e2c47e5321
Create Date: 2023-05-24 23:55:59.116922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf9d71262c3f'
down_revision = 'c4e2c47e5321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_constraint('entries_food_selection_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'foods', ['food_selection'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('entries_food_selection_fkey', 'foods', ['food_selection'], ['food_name'])

    # ### end Alembic commands ###
