"""empty message

Revision ID: c4e2c47e5321
Revises: ca1aa385c050
Create Date: 2023-05-24 23:54:06.449232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e2c47e5321'
down_revision = 'ca1aa385c050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_constraint('entries_food_selection_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'foods', ['food_selection'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('entries_food_selection_fkey', 'foods', ['food_selection'], ['food_name'])

    # ### end Alembic commands ###
