"""empty message

Revision ID: ea3c2d7fd763
Revises: 913230a68b16
Create Date: 2023-05-24 23:25:45.497458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea3c2d7fd763'
down_revision = '913230a68b16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('fullname', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_fullname'), ['fullname'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    with op.batch_alter_table('food_tracker_users', schema=None) as batch_op:
        batch_op.drop_index('ix_food_tracker_users_fullname')
        batch_op.drop_index('ix_food_tracker_users_username')

    op.drop_table('food_tracker_users')
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_constraint('entries_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('entries_user_id_fkey', 'food_tracker_users', ['user_id'], ['id'])

    op.create_table('food_tracker_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_image', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('fullname', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='food_tracker_users_pkey')
    )
    with op.batch_alter_table('food_tracker_users', schema=None) as batch_op:
        batch_op.create_index('ix_food_tracker_users_username', ['username'], unique=False)
        batch_op.create_index('ix_food_tracker_users_fullname', ['fullname'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_fullname'))

    op.drop_table('users')
    # ### end Alembic commands ###
